import os
from PyQt5.QtWidgets import QLabel,QHBoxLayout,QVBoxLayout,QPushButton,QApplication,QLineEdit,QComboBox,QScrollArea,QWidget
from PyQt5.QtGui import QIcon,QPixmap,QColor,QFont
from PyQt5.QtCore import Qt
from Langauge_packs import Languages

app = QApplication([])
def find_file(file):
    "Return path to file"
    Path = os.path.join(os.environ.get("_MEIPASS2",os.path.abspath(".")),file).replace("\\","/")
    return Path
Icon = QIcon(find_file("Images/Icon.ico"))
White_color = QColor(255,255,255)
Font = QFont("Aeral",15)
Title_font = QFont("Aeral",25)
backgrounds = """QWidget{
        background-image:url("""+find_file("Images/galaxy.jpg")+""");
        background-color:;
    }
    QPushButton {
        background-image:url("""+find_file("Images/button background.png")+""");
        color:white;
        border:1px solid black;
        background-repeat: no repeat;
    }
    QLineEdit{      
        color:white;
        border:1px solid black;
    }
    QLabel{
        background-image:url("""+find_file("Images/label background.png.bmp")+""");
        color:white;
    }
    QComboBox{
        background-image:url("""+find_file("Images/label background.png.bmp")+""");
        color-white;
        border:2px solid white;
    }"""
levels_backgrounds = """QWidget{
        background-image:url("""+find_file("Images/label background.png.bmp")+""");
        background-color:;
    }
    QPushButton {
        background-image:url("""+find_file("Images/button background.png")+""");
        color:white;
        border:1px solid black;
        background-repeat: no repeat;
    }
    QLabel{
        background-image:url("""+find_file("Images/label background.png.bmp")+""");
        color:white;
    }
    QScrollArea{
        background-color:transparent;
        border:green;
    }
   """
menu_buttons_background = "QPushButton{background-image:url("+find_file("Images/button long-background.png")+")}"

Choose_language =QComboBox()
Choose_language.addItems(["None","English","Українська"])
Choose_language.setMinimumWidth(75)
Select_language_text = QLabel("Select language to continue")
Select_language_text.setFont(Font)
main_select_language_layout = QVBoxLayout()
main_select_language_layout.addStretch(1)
main_select_language_layout.addWidget(Select_language_text,alignment=Qt.AlignHCenter)
main_select_language_layout.addWidget(Choose_language,alignment=Qt.AlignHCenter)
main_select_language_layout.addStretch(1)
def create_layouts(Language):
    #Start window
    Space_war_image = QPixmap(find_file("Images/Space_war.jpg"))
    button_start =QPushButton()
    button_start.setText(Languages[Language]["Start_window"][0])
    button_start.setMinimumWidth(100)
    button_change_language = QPushButton(Languages[Language]["Start_window"][1])
    start_buttons_layout = QHBoxLayout()
    start_buttons_layout.addStretch(1)
    start_buttons_layout.addWidget(button_start,alignment=Qt.AlignHCenter)
    start_buttons_layout.addStretch(1)
    start_buttons_layout.addWidget(button_change_language,alignment=Qt.AlignRight)
    start_buttons_layout.setContentsMargins(50,10,10,10)
    Space_war_label = QLabel()
    Space_war_label.setPixmap(Space_war_image)
    main_start_layout = QVBoxLayout()
    main_start_layout.addWidget(Space_war_label,alignment=Qt.AlignHCenter|Qt.AlignTop)
    main_start_layout.addStretch(1)
    main_start_layout.addLayout(start_buttons_layout)
    main_start_layout.addStretch(4)

    #login and create account window
    Line_user_name = QLineEdit("")
    Line_user_name.setPlaceholderText(Languages[Language]["Login_window"][0])
    Line_user_name.setMaximumWidth(100)
    Line_password = QLineEdit("")
    Line_password.setPlaceholderText(Languages[Language]["Login_window"][1])
    Line_password.setMaximumWidth(100)
    Button_check = QPushButton()
    Button_check.setText(Languages[Language]["Login_window"][2])
    Button_check.setMinimumWidth(75)
    Button_login_or_create = QPushButton(Languages[Language]["Login_window"][3])
    Button_login_or_create.setMinimumWidth(75)
    Login_text = QLabel(Languages[Language]["Login_window"][4])
    Login_text.setFont(Font)
    main_create_and_login_account_layout = QVBoxLayout()
    main_create_and_login_account_layout.addStretch(1)
    main_create_and_login_account_layout.addWidget(Login_text,alignment=Qt.AlignHCenter)
    main_create_and_login_account_layout.addStretch(1)
    main_create_and_login_account_layout.addWidget(Line_user_name,alignment=Qt.AlignHCenter)
    main_create_and_login_account_layout.addWidget(Line_password,alignment=Qt.AlignHCenter)
    main_create_and_login_account_layout.addWidget(Button_check,alignment=Qt.AlignHCenter)
    main_create_and_login_account_layout.addWidget(Button_login_or_create,alignment=Qt.AlignHCenter)
    main_create_and_login_account_layout.addStretch(1)

    #Menu window   
    players_name = QLabel("")
    players_name.setFont(Font)
    players_money_icon = QLabel()
    players_money_icon.setPixmap(QPixmap(find_file("Images/money_icon.png")).scaled(30,30,Qt.KeepAspectRatio))
    players_money = QLabel("")
    players_money.setFont(Title_font)
    players_layout = QHBoxLayout()
    players_layout.addWidget(players_name)
    players_layout.addStretch(1)
    players_layout.addWidget(players_money_icon)
    players_layout.addWidget(players_money)

    level_1_text = QLabel(Languages[Language]["Menu_and_levels"]["Levels"][0])
    level_1_text.setFont(Font)
    level_1_description_image = QPixmap(find_file("Images/level_1_description.png"))
    level_1_description_image = level_1_description_image.scaled(400,400,Qt.KeepAspectRatio)
    level_1_description = QLabel()
    level_1_description.resize(50,50)
    level_1_description.setPixmap(level_1_description_image)
    Button_level_1 = QPushButton(Languages[Language]["Menu_and_levels"]["Levels"][0])
    Button_level_1.setMinimumWidth(75)
    level_1_layout = QVBoxLayout()
    level_1_layout.addWidget(level_1_text,alignment= Qt.AlignHCenter)
    level_1_layout.addWidget(level_1_description,alignment= Qt.AlignHCenter | Qt.AlignVCenter)
    level_1_layout.addWidget(Button_level_1,alignment= Qt.AlignHCenter)
    level_1_layout.setContentsMargins(50,50,50,50)
    level_1_window = QWidget() 
    level_1_window.setLayout(level_1_layout)
    level_1_window.setStyleSheet(levels_backgrounds)

    level_2_text = QLabel(Languages[Language]["Menu_and_levels"]["Levels"][1])
    level_2_text.setFont(Font)
    level_2_description_image = QPixmap(find_file("Images/level_2_description.png"))
    level_2_description_image = level_2_description_image.scaled(400,400,Qt.KeepAspectRatio)
    level_2_description = QLabel()
    level_2_description.resize(50,50)
    level_2_description.setPixmap(level_2_description_image)
    Button_level_2 = QPushButton(Languages[Language]["Menu_and_levels"]["Levels"][1])
    Button_level_2.setMinimumWidth(75)
    level_2_layout = QVBoxLayout()
    level_2_layout.addWidget(level_2_text,alignment= Qt.AlignHCenter)
    level_2_layout.addWidget(level_2_description,alignment= Qt.AlignHCenter | Qt.AlignVCenter)
    level_2_layout.addWidget(Button_level_2,alignment= Qt.AlignHCenter)
    level_2_layout.setContentsMargins(50,50,50,50)
    level_2_window = QWidget() 
    level_2_window.setLayout(level_2_layout)
    level_2_window.setStyleSheet(levels_backgrounds)

    level_3_text = QLabel(Languages[Language]["Menu_and_levels"]["Levels"][2])
    level_3_text.setFont(Font)
    level_3_description_image = QPixmap(find_file("Images/level_3_description.png"))
    level_3_description_image = level_3_description_image.scaled(400,400,Qt.KeepAspectRatio)
    level_3_description = QLabel()
    level_3_description.resize(50,50)
    level_3_description.setPixmap(level_3_description_image)
    Button_level_3 = QPushButton(Languages[Language]["Menu_and_levels"]["Levels"][2])
    Button_level_3.setMinimumWidth(75)
    level_3_layout = QVBoxLayout()
    level_3_layout.addWidget(level_3_text,alignment= Qt.AlignHCenter)
    level_3_layout.addWidget(level_3_description,alignment= Qt.AlignHCenter | Qt.AlignVCenter)
    level_3_layout.addWidget(Button_level_3,alignment= Qt.AlignHCenter)
    level_3_layout.setContentsMargins(50,50,50,50)
    level_3_window = QWidget() 
    level_3_window.setLayout(level_3_layout)
    level_3_window.setStyleSheet(levels_backgrounds)

    level_4_text = QLabel(Languages[Language]["Menu_and_levels"]["Levels"][3])
    level_4_text.setFont(Font)
    level_4_description_image = QPixmap(find_file("Images/level_4_description.png"))
    level_4_description_image = level_4_description_image.scaled(400,400,Qt.KeepAspectRatio)
    level_4_description = QLabel()
    level_4_description.resize(50,50)
    level_4_description.setPixmap(level_4_description_image)
    Button_level_4 = QPushButton(Languages[Language]["Menu_and_levels"]["Levels"][3])
    Button_level_4.setMinimumWidth(75)
    level_4_layout = QVBoxLayout()
    level_4_layout.addWidget(level_4_text,alignment= Qt.AlignHCenter)
    level_4_layout.addWidget(level_4_description,alignment= Qt.AlignHCenter | Qt.AlignVCenter)
    level_4_layout.addWidget(Button_level_4,alignment= Qt.AlignHCenter)
    level_4_layout.setContentsMargins(50,50,50,50)
    level_4_window = QWidget() 
    level_4_window.setLayout(level_4_layout)
    level_4_window.setStyleSheet(levels_backgrounds)

    Button_upgrade_ship = QPushButton(Languages[Language]["Menu_and_levels"]["Menu"][0])
    Button_upgrade_ship.setStyleSheet(menu_buttons_background)
    Button_upgrade_ship.setMaximumWidth(130)
    Button_tips = QPushButton(Languages[Language]["Menu_and_levels"]["Menu"][1])
    Button_tips.setMinimumWidth(100)
    Button_tips.setMaximumWidth(130)
    Button_tips.setStyleSheet(menu_buttons_background)
    Button_best_players = QPushButton(Languages[Language]["Menu_and_levels"]["Menu"][2])
    Button_best_players.setStyleSheet(menu_buttons_background)
    Button_best_players.setMaximumWidth(130)
    Buttons_layout = QHBoxLayout()
    Buttons_layout.addWidget(Button_upgrade_ship)
    Buttons_layout.addWidget(Button_tips)
    Buttons_layout.addWidget(Button_best_players)
    Buttons_layout.setContentsMargins(10,10,10,10)

    main_scroll_layout = QHBoxLayout()
    main_scroll_layout.addWidget(level_1_window)
    main_scroll_layout.addWidget(level_2_window)
    main_scroll_layout.addWidget(level_3_window)
    main_scroll_layout.addWidget(level_4_window)
    main_scroll_layout.setContentsMargins(30,30,30,30)
    scroll_window = QWidget() 
    scroll_window.setLayout(main_scroll_layout)
    scroll_window.setStyleSheet(levels_backgrounds)
    scroll_area = QScrollArea()
    scroll_area.setWidgetResizable(True)
    scroll_area.setHorizontalScrollBarPolicy(Qt.ScrollBarPolicy.ScrollBarAlwaysOn)
    scroll_area.setVerticalScrollBarPolicy(Qt.ScrollBarPolicy.ScrollBarAlwaysOff)
    scroll_area.setWidget(scroll_window)
    scroll_area.setStyleSheet(levels_backgrounds)
    main_menu_layout = QVBoxLayout()
    main_menu_layout.addLayout(players_layout)
    main_menu_layout.addWidget(scroll_area)
    main_menu_layout.addLayout(Buttons_layout)

    #Tips window
    Tip_title_keys = QLabel(Languages[Language]["Menu_and_levels"]["Menu"][3])
    Tip_title_keys.setFont(Title_font)
    Press_button_A_text = QLabel(Languages[Language]["Menu_and_levels"]["Menu"][4])
    Press_button_A_text.setFont(Font)
    Press_button_D_text = QLabel(Languages[Language]["Menu_and_levels"]["Menu"][5])
    Press_button_D_text.setFont(Font)
    Press_SPACE_text = QLabel(Languages[Language]["Menu_and_levels"]["Menu"][6])
    Press_SPACE_text.setFont(Font)
    keys_layout = QVBoxLayout()
    keys_layout.addWidget(Tip_title_keys,alignment=Qt.AlignHCenter)
    keys_layout.addWidget(Press_button_A_text,alignment=Qt.AlignLeft)
    keys_layout.addWidget(Press_button_D_text,alignment=Qt.AlignLeft)
    keys_layout.addWidget(Press_SPACE_text,alignment=Qt.AlignLeft)
    keys_window = QWidget()
    keys_window.setLayout(keys_layout)
    keys_layout.setContentsMargins(20,20,20,20)
    Tip_title_enemies = QLabel(Languages[Language]["Menu_and_levels"]["Menu"][7])
    Tip_title_enemies.setFont(Title_font)
    basic_enemy_image = QLabel()
    basic_enemy_image.setPixmap(QPixmap(find_file("Images/ufo.png")).scaled(100,100,Qt.KeepAspectRatio))
    basic_enemy_text = QLabel(Languages[Language]["Menu_and_levels"]["Menu"][8])
    basic_enemy_text.setWordWrap(True)
    basic_enemy_layout = QHBoxLayout()
    basic_enemy_layout.addWidget(basic_enemy_image,alignment=Qt.AlignLeft)
    basic_enemy_layout.addWidget(basic_enemy_text,alignment=Qt.AlignLeft)
    basic_enemy_layout.setContentsMargins(0,40,0,40)
    basic_enemy_window = QWidget()
    basic_enemy_window.setLayout(basic_enemy_layout)
    elite_enemy_image = QLabel()
    elite_enemy_image.setPixmap(QPixmap(find_file("Images/elite ufo.png")).scaled(100,100,Qt.KeepAspectRatio))
    elite_enemy_text = QLabel(Languages[Language]["Menu_and_levels"]["Menu"][9])
    elite_enemy_text.setWordWrap(True)
    elite_enemy_layout = QHBoxLayout()
    elite_enemy_layout.addWidget(elite_enemy_image,alignment=Qt.AlignLeft)
    elite_enemy_layout.addWidget(elite_enemy_text,alignment=Qt.AlignLeft)
    elite_enemy_layout.setContentsMargins(0,40,0,40)
    elite_enemy_window = QWidget()
    elite_enemy_window.setLayout(elite_enemy_layout)
    first_boss_image = QLabel()
    first_boss_image.setPixmap(QPixmap(find_file("Images/First boss.png")).scaled(100,100,Qt.KeepAspectRatio))
    first_boss_text = QLabel(Languages[Language]["Menu_and_levels"]["Menu"][17])
    first_boss_text.setWordWrap(True)
    first_boss_layout = QHBoxLayout()
    first_boss_layout.addWidget(first_boss_image)
    first_boss_layout.addWidget(first_boss_text,alignment=Qt.AlignLeft)
    first_boss_layout.setContentsMargins(0,40,0,40)
    first_boss_window = QWidget()
    first_boss_window.setLayout(first_boss_layout)
    damager_image = QLabel()
    damager_image.setPixmap(QPixmap(find_file("Images/damager.png")).scaled(100,100,Qt.KeepAspectRatio))
    damager_text = QLabel(Languages[Language]["Menu_and_levels"]["Menu"][18])
    damager_text.setWordWrap(True)
    damager_layout = QHBoxLayout()
    damager_layout.addWidget(damager_image)
    damager_layout.addWidget(damager_text,alignment=Qt.AlignLeft)
    damager_layout.setContentsMargins(0,40,0,40)
    damager_window = QWidget()
    damager_window.setLayout(damager_layout)
    last_boss_image = QLabel()
    last_boss_image.setPixmap(QPixmap(find_file("Images/Last boss.png")).scaled(100,100,Qt.KeepAspectRatio))
    last_boss_text = QLabel(Languages[Language]["Menu_and_levels"]["Menu"][19])
    last_boss_text.setWordWrap(True)
    last_boss_layout = QHBoxLayout()
    last_boss_layout.addWidget(last_boss_image)
    last_boss_layout.addWidget(last_boss_text,alignment=Qt.AlignLeft)
    last_boss_layout.setContentsMargins(0,40,0,20)
    last_boss_window = QWidget()
    last_boss_window.setLayout(last_boss_layout)
    enemies_layout = QVBoxLayout()
    enemies_layout.addWidget(Tip_title_enemies,alignment=Qt.AlignHCenter)
    enemies_layout.addWidget(basic_enemy_window)
    enemies_layout.addWidget(elite_enemy_window)
    enemies_layout.addWidget(first_boss_window)
    enemies_layout.addWidget(damager_window)
    enemies_layout.addWidget(last_boss_window)
    enemies_layout.setContentsMargins(20,20,20,20)
    enemies_window = QWidget()
    enemies_window.setLayout(enemies_layout)

    scroll_tip_layout = QVBoxLayout()
    scroll_tip_layout.addWidget(keys_window)
    scroll_tip_layout.addWidget(enemies_window)
    Tip_scroll_window = QWidget()
    Tip_scroll_window.setLayout(scroll_tip_layout)
    Tip_scroll_area = QScrollArea()
    Tip_scroll_area.setWidgetResizable(True)
    Tip_scroll_area.setVerticalScrollBarPolicy(Qt.ScrollBarPolicy.ScrollBarAlwaysOn)
    Tip_scroll_area.setHorizontalScrollBarPolicy(Qt.ScrollBarPolicy.ScrollBarAlwaysOff)
    Tip_scroll_area.setWidget(Tip_scroll_window)
    Tip_scroll_area.setStyleSheet(levels_backgrounds)
    main_tip_layout = QVBoxLayout()
    main_tip_layout.addWidget(Tip_scroll_area)

    #Upgrade ship window
    rocket_image = QLabel()
    rocket_image.setPixmap(QPixmap(find_file("Images/rocket.png")).scaled(200,350,Qt.KeepAspectRatio))
    rocket_layout = QVBoxLayout()
    rocket_layout.addWidget(rocket_image)
    rocket_level_text = QLabel("")
    rocket_level_text.setFont(Title_font)
    rocket_hp_image = QLabel()
    rocket_hp_image.setPixmap(QPixmap(find_file("Images/Hp.png")).scaled(50,50,Qt.KeepAspectRatio))
    rocket_hp_amount = QLabel("")
    rocket_hp_amount.setFont(Title_font)
    rocket_hp_layout = QHBoxLayout()
    rocket_hp_layout.addWidget(rocket_hp_image,alignment=Qt.AlignLeft)
    rocket_hp_layout.addWidget(rocket_hp_amount)
    rocket_speed_image = QLabel()
    rocket_speed_image.setPixmap(QPixmap(find_file("Images/Rocket_speed_image.png")).scaled(50,50,Qt.KeepAspectRatio))
    rocket_speed_amount = QLabel("")
    rocket_speed_amount.setFont(Title_font)
    rocket_speed_layout = QHBoxLayout()
    rocket_speed_layout.addWidget(rocket_speed_image,alignment=Qt.AlignLeft)
    rocket_speed_layout.addWidget(rocket_speed_amount)
    rocket_damage_image = QLabel()
    rocket_damage_image.setPixmap(QPixmap(find_file("Images/damage icon.png")).scaled(50,50,Qt.KeepAspectRatio))
    rocket_damage_amount = QLabel("")
    rocket_damage_amount.setFont(Title_font)
    rocket_damage_layout = QHBoxLayout()
    rocket_damage_layout.addWidget(rocket_damage_image,alignment=Qt.AlignLeft)
    rocket_damage_layout.addWidget(rocket_damage_amount)
    rocket_ammo_image = QLabel()
    rocket_ammo_image.setPixmap(QPixmap(find_file("Images/ammo amount.png")).scaled(50,50,Qt.KeepAspectRatio))
    rocket_ammo_amount = QLabel("")
    rocket_ammo_amount.setFont(Font)
    rocket_ammo_layout = QHBoxLayout()
    rocket_ammo_layout.addWidget(rocket_ammo_image,alignment=Qt.AlignLeft)
    rocket_ammo_layout.addWidget(rocket_ammo_amount)
    Button_upgrade = QPushButton(Languages[Language]["Menu_and_levels"]["Menu"][10])
    Button_upgrade.setMaximumWidth(100)
    Button_upgrade.setMaximumWidth(100)
    upgrade_cost_icon = QLabel()
    upgrade_cost_icon.setPixmap(QPixmap(find_file("Images/money_icon.png")).scaled(50,50,Qt.KeepAspectRatio))
    upgrade_cost_amount = QLabel("")
    upgrade_cost_amount.setFont(Title_font)
    upgrade_cost_layout = QHBoxLayout()
    upgrade_cost_layout.addWidget(upgrade_cost_icon,alignment=Qt.AlignLeft)
    upgrade_cost_layout.addWidget(upgrade_cost_amount)
    rocket_characteristics_layout = QVBoxLayout()
    rocket_characteristics_layout.addWidget(rocket_level_text,alignment=Qt.AlignLeft)
    rocket_characteristics_layout.addLayout(rocket_hp_layout,)
    rocket_characteristics_layout.addLayout(rocket_speed_layout)
    rocket_characteristics_layout.addLayout(rocket_damage_layout)
    rocket_characteristics_layout.addLayout(rocket_ammo_layout)
    rocket_characteristics_layout.addLayout(upgrade_cost_layout)
    rocket_characteristics_layout.addWidget(Button_upgrade,alignment=Qt.AlignLeft)
    main_upgrade_ship_layout = QHBoxLayout()
    main_upgrade_ship_layout.addLayout(rocket_layout)
    main_upgrade_ship_layout.addLayout(rocket_characteristics_layout)

    #Subtitles window
    title_image = QLabel()
    title_image.setPixmap(QPixmap(find_file("Images/Space_war.jpg")).scaled(400,250,Qt.KeepAspectRatio))
    congratulation_text = QLabel(Languages[Language]["Subtitles_window"][0])
    congratulation_text.setFont(Title_font)
    subtitles_text = QLabel(Languages[Language]["Subtitles_window"][1])
    subtitles_text.setFont(Title_font)
    subtitles_text.setWordWrap(True)
    Button_back = QPushButton(Languages[Language]["Subtitles_window"][2])
    Button_back.setMaximumWidth(100)
    main_subtitles_window_layout = QVBoxLayout()
    main_subtitles_window_layout.addWidget(title_image,alignment=Qt.AlignHCenter)
    main_subtitles_window_layout.addWidget(congratulation_text,alignment=Qt.AlignHCenter)
    main_subtitles_window_layout.addWidget(subtitles_text,alignment=Qt.AlignHCenter)
    main_subtitles_window_layout.addWidget(Button_back,alignment=Qt.AlignHCenter)
    return button_start,button_change_language,main_start_layout,\
        Line_user_name,Line_password,Button_check,Button_login_or_create,Login_text,main_create_and_login_account_layout,\
            Button_level_1,Button_level_2,Button_level_3,Button_level_4,players_name,players_money,Button_upgrade_ship,Button_tips,Button_best_players,main_menu_layout,level_1_layout,level_2_layout,level_3_layout,level_4_layout,\
                main_tip_layout,main_upgrade_ship_layout,Button_upgrade,rocket_level_text,rocket_hp_amount,rocket_speed_amount,rocket_damage_amount,rocket_ammo_amount,upgrade_cost_amount,\
                    Button_back,main_subtitles_window_layout

